import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({ executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe', headless:true, args:['--no-sandbox'] });
const p = await b.newPage();
await p.setViewport({ width: 470, height: 1000, deviceScaleFactor: 2 });
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto(process.argv[2], { waitUntil:'domcontentloaded', timeout:30000 });
await new Promise(r=>setTimeout(r,2500));
const el = await p.$('.receipt');
if (el) await el.screenshot({ path: process.argv[3] });
else await p.screenshot({ path: process.argv[3] });
console.log(el ? 'receipt captured' : 'NO .receipt element', errs.length?('errors: '+errs):'');
await b.close();
