//! RENDER STATE -- `tsp_state.py` (`codes`, `predict`, `state_key`, `BLEND_PRESET`, `HOST`) ported verbatim, and
//! `tape_to_seq.WorldTemplate` (`__init__` / `select`) served from FROZEN constants instead of a runtime pack:
//! `src/frozen/world_4445.json`, generated by `tools/freeze_template.py` from `capgate/frame_4445.pack`
//! (sha256 2399a079a7768d1f49a35e86b68c1e9bc380daeac6c042c24fff069409ff6ad6). Every state tuple, shader/layout
//! hash, PS constant buffer and preamble draw is byte-for-byte what `WorldTemplate.__init__` lifts.
use crate::util::OrderedMap;
use serde_json::{Map, Value};
use std::collections::{BTreeMap, HashMap};

pub const FROZEN_WORLD_4445: &str = include_str!("frozen/world_4445.json");

/// tsp_state.BLEND_PRESET: (src<<4 | dst) -> host blend preset (FUN_140844220 / FUN_140842e30).
fn blend_preset(key: u32) -> u32 {
    match key { 0x10 => 1, 0x11 => 0x11, 0x16 => 0x11, 0x14 => 0x12, 0x41 => 0x12, 0x46 => 0x12,
                0x21 => 0x16, 0x22 => 0x22, 0x30 => 7, 0x31 => 0x19, 0x45 => 0x32, _ => 0 }
}

/// tsp_state.codes(): the integers Steam hands its host renderer for one polygon group (CONFIRMED).
#[derive(Clone, Debug)]
pub struct Codes { pub blend_key: u32, pub blend: u32, pub samp: u32, pub filt: u32, pub addr: u32, pub cat: u32, pub s19: u32,
                   pub depth: u32, pub cull: Option<u32>, pub ignore_texa: u32, pub fog: u32, pub zwrite_disabled: u32, pub listtype: u32 }

pub fn codes(pcw: u32, isp: u32, tsp: u32, gflags: u32, alpha_mult: f64, kind: u32, uvmode: u32) -> Codes {
    let (src, dst) = if alpha_mult == 1.0 { (tsp >> 29, (tsp >> 26) & 7) } else { (4, 5) };   // ctx+0x1f8274 = 0x45
    let blend_key = src << 4 | dst;
    let blend = blend_preset(blend_key);
    let clamp = if uvmode == 4 { 0 } else { (tsp >> 15) & 3 };
    let mut addr = if clamp == 3 { 1 } else { 0 };
    if tsp & 0x60000 != 0 { addr = 2; }
    let filt = (tsp >> 13) & 3;
    let samp = (if filt == 0 { 0x10000 } else { 0 }) | addr << 17;
    let listtype = (pcw >> 24) & 7;
    let (cat, s19) = if listtype == 0 {
        if kind != 3 { (0, 0) } else { (if alpha_mult == 1.0 { 0 } else { 3 }, 1) }
    } else if listtype == 1 { (1, 0) } else { (3, 0) };
    let zwrite_disabled = (isp >> 26) & 1;
    let depth = if cat == 2 { 10 } else if zwrite_disabled == 0 {
        if cat == 3 && s19 == 0 { 2 } else { 4 - ((pcw >> 7) & 1) }
    } else { 2 };
    let cull = if (0..=3).contains(&kind) { Some(gflags & 3) } else { None };
    let ignore_texa = if (tsp >> 19) & 1 != 0 { 1 } else if src == 1 && dst != 0 { 1 } else { 0 };
    let fog = (tsp >> 22) & 3;
    Codes { blend_key, blend, samp, filt, addr, cat, s19, depth, cull, ignore_texa, fog, zwrite_disabled, listtype }
}

/// tsp_state.predict(): HOST translation of the codes (INFERRED table from the capture gate; unmapped -> None).
#[derive(Clone, Debug, Default)]
pub struct Pred { pub blend: Option<(i64, i64)>, pub samp: Option<(i64, i64, i64)>, pub depth: Option<(i64, i64)>,
                  pub cull: Option<i64>, pub ps: Option<String>, pub codes: Option<Codes> }

pub fn predict(pcw: u32, isp: u32, tsp: u32, gflags: u32, kind: u32, alpha_mult: f64) -> Pred {
    let c = codes(pcw, isp, tsp, gflags, alpha_mult, kind, 0);
    let blend = match c.blend { 1 => Some((5, 6)), 0x12 => Some((5, 2)), 0x32 => Some((5, 6)), _ => None };
    let samp = match c.samp { 0x00000 => Some((21, 1, 1)), 0x10000 => Some((0, 1, 1)), 0x20000 => Some((21, 3, 3)), 0x30000 => Some((0, 3, 3)), _ => None };
    let depth = match c.depth { 2 => Some((0, 0)), 4 => Some((1, 1)), _ => None };
    let cull = c.cull.and_then(|w| match w { 0 => Some(1), 1 => Some(1), 2 => Some(2), 3 => Some(3), _ => None });
    let ps = Some(if c.ignore_texa == 1 { "opaque".to_string() } else { "texalpha".to_string() });
    Pred { blend, samp, depth, cull, ps, codes: Some(c) }
}

impl Pred {
    /// tsp_state.FIELDS all present (`full` in WorldTemplate.select).
    pub fn full(&self) -> bool { self.ps.is_some() && self.samp.is_some() && self.blend.is_some() && self.depth.is_some() && self.cull.is_some() }
    /// tsp_state.state_key of `dict(pred, ps=ps)` as a string; None unless full.
    pub fn state_key(&self, ps: &str) -> Option<String> {
        let (s, b, d, c) = (self.samp?, self.blend?, self.depth?, self.cull?);
        Some(format!("{}|{},{},{}|{},{}|{},{}|{}", ps, s.0, s.1, s.2, b.0, b.1, d.0, d.1, c))
    }
}

fn state_key_of_json(k: &Value) -> Option<String> {
    let a = k.as_array()?;
    let ps = a.get(0)?.as_str()?;
    let s = a.get(1)?.as_array()?; let b = a.get(2)?.as_array()?; let d = a.get(3)?.as_array()?; let c = a.get(4)?.as_i64()?;
    let g = |v: &Vec<Value>, i: usize| v.get(i).and_then(|x| x.as_i64());
    Some(format!("{}|{},{},{}|{},{}|{},{}|{}", ps, g(s, 0)?, g(s, 1)?, g(s, 2)?, g(b, 0)?, g(b, 1)?, g(d, 0)?, g(d, 1)?, c))
}

fn hex(s: &str) -> Vec<u8> { (0..s.len() / 2).map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap_or(0)).collect() }

/// `tape_to_seq.WorldTemplate` from the frozen constants.
pub struct WorldTemplate {
    pub pack: String, pub pack_sha256: String,
    pub input_layouts: Value,
    /// psVariant -> the first vs_world draw's KEYS (insertion order = `next(iter(self.draw))` fallback)
    pub draw: OrderedMap<Map<String, Value>>,
    /// psVariant -> the PS constant buffers (None where the Python keeps None)
    pub pscb: HashMap<String, Vec<Option<Vec<u8>>>>,
    by_state: HashMap<String, Map<String, Value>>,
    /// the three frame-preamble draws (KEYS + vscbHash + pscbHash) and their constant buffers
    pub preamble: Vec<Map<String, Value>>,
    pub preamble_cb: Vec<Vec<(String, Vec<u8>)>>,
}

impl WorldTemplate {
    pub fn frozen() -> WorldTemplate { Self::from_json(FROZEN_WORLD_4445).expect("frozen world_4445.json") }

    pub fn from_json(s: &str) -> Result<WorldTemplate, String> {
        let v: Value = serde_json::from_str(s).map_err(|e| format!("world template json: {e}"))?;
        let mut draw = OrderedMap::new();
        if let Some(m) = v.get("draw").and_then(|x| x.as_object()) {
            for (k, d) in m { draw.insert_new(k, d.as_object().cloned().unwrap_or_default()); }
        }
        let mut pscb = HashMap::new();
        if let Some(m) = v.get("pscb").and_then(|x| x.as_object()) {
            for (k, l) in m {
                pscb.insert(k.clone(), l.as_array().map(|a| a.iter().map(|x| x.as_str().map(hex)).collect()).unwrap_or_default());
            }
        }
        let mut by_state = HashMap::new();
        if let Some(a) = v.get("by_state").and_then(|x| x.as_array()) {
            for e in a {
                if let (Some(k), Some(d)) = (e.get(0).and_then(state_key_of_json), e.get(1).and_then(|x| x.as_object())) {
                    by_state.entry(k).or_insert_with(|| d.clone());
                }
            }
        }
        let preamble: Vec<Map<String, Value>> = v.get("preamble").and_then(|x| x.as_array())
            .map(|a| a.iter().filter_map(|d| d.as_object().cloned()).collect()).unwrap_or_default();
        let preamble_cb: Vec<Vec<(String, Vec<u8>)>> = v.get("preamble_cb").and_then(|x| x.as_array())
            .map(|a| a.iter().map(|m| m.as_object().map(|o| o.iter().map(|(h, b)| (h.clone(), hex(b.as_str().unwrap_or("")))).collect()).unwrap_or_default()).collect())
            .unwrap_or_default();
        Ok(WorldTemplate {
            pack: v.get("pack").and_then(|x| x.as_str()).unwrap_or("").to_string(),
            pack_sha256: v.get("pack_sha256").and_then(|x| x.as_str()).unwrap_or("").to_string(),
            input_layouts: v.get("inputLayouts").cloned().unwrap_or(Value::Null),
            draw, pscb, by_state, preamble, preamble_cb,
        })
    }

    /// `WorldTemplate.select(pred, stats)`: the captured draw whose state equals the prediction exactly, else
    /// the ps-variant fallback with the predicted fields patched in. Returns (draw KEYS dict, ps variant).
    pub fn select(&self, pred: &Pred, stats: &mut BTreeMap<String, u64>) -> (Map<String, Value>, String) {
        let ps = match &pred.ps { Some(p) if self.draw.contains(p) => p.clone(), _ => self.draw.keys.first().cloned().unwrap_or_default() };
        let full = pred.full();
        if full {
            if let Some(k) = pred.state_key(&ps) {
                if let Some(hit) = self.by_state.get(&k) {
                    *stats.entry("exact captured state".into()).or_insert(0) += 1;
                    return (hit.clone(), ps);
                }
            }
        }
        let mut d = self.draw.get(&ps).cloned().unwrap_or_default();
        if let Some(s) = pred.samp {
            if let Some(arr) = d.get_mut("samp").and_then(|x| x.as_array_mut()) {
                if let Some(s0) = arr.get_mut(0).and_then(|x| x.as_object_mut()) {
                    s0.insert("filter".into(), Value::from(s.0)); s0.insert("u".into(), Value::from(s.1));
                    s0.insert("v".into(), Value::from(s.2)); s0.insert("w".into(), Value::from(s.2));
                }
            }
        }
        if let Some(b) = pred.blend {
            if let Some(o) = d.get_mut("blend").and_then(|x| x.as_object_mut()) { o.insert("src".into(), Value::from(b.0)); o.insert("dst".into(), Value::from(b.1)); }
        }
        if let Some(dp) = pred.depth {
            if let Some(o) = d.get_mut("depth").and_then(|x| x.as_object_mut()) { o.insert("write".into(), Value::from(dp.0)); o.insert("sten".into(), Value::from(dp.1)); }
        }
        if let Some(c) = pred.cull.filter(|&c| c != 0) {   // Python truthiness of `pred.get('cull')`
            if let Some(o) = d.get_mut("raster").and_then(|x| x.as_object_mut()) { o.insert("cull".into(), Value::from(c)); }
        }
        *stats.entry(if full { "patched fallback".to_string() } else { "partial (unmapped code or no group)".to_string() }).or_insert(0) += 1;
        (d, ps)
    }
}
