#!/usr/bin/env python3
"""
gen_def.py -- regenerate version_proxy.def from a REAL version.dll.

Parses the export directory of a genuine version.dll (e.g. the Proton prefix's
system32\\version.dll) and emits forwarder lines "Name=versionorig.Name @ord"
for every export. Pure stdlib PE parsing, no pip deps.

  python3 gen_def.py /path/to/real/version.dll > version_proxy.def

The forward target module name (default "versionorig") must match the renamed
copy that setup_proxy.sh drops next to the game exe.
"""
import struct, sys

FWD_TARGET = "versionorig"

def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_def.py <real version.dll> [fwd_target]")
    d = open(sys.argv[1], "rb").read()
    target = sys.argv[2] if len(sys.argv) > 2 else FWD_TARGET
    e = struct.unpack_from("<I", d, 0x3c)[0]
    coff = e + 4
    nsec = struct.unpack_from("<H", d, coff + 2)[0]
    optsz = struct.unpack_from("<H", d, coff + 16)[0]
    opt = coff + 20
    magic = struct.unpack_from("<H", d, opt)[0]
    pe32plus = magic == 0x20b
    ddoff = opt + (112 if pe32plus else 96)
    exp_rva = struct.unpack_from("<I", d, ddoff)[0]
    sec = opt + optsz
    S = []
    for i in range(nsec):
        o = sec + i * 40
        vsz, vrva, rawsz, rawptr = struct.unpack_from("<IIII", d, o + 8)
        S.append((vrva, vsz, rawptr, rawsz))
    def r2o(rva):
        for vrva, vsz, rawptr, rawsz in S:
            if vrva <= rva < vrva + max(vsz, rawsz):
                return rawptr + (rva - vrva)
        return None
    def cstr(o):
        ee = d.index(b"\0", o)
        return d[o:ee].decode(errors="replace")
    o = r2o(exp_rva)
    (_, _, _, _, _nameRVA, ordbase, _nfun, nnames,
     _af, an_rva, ao_rva) = struct.unpack_from("<IIHHIIIIIII", d, o)
    no = r2o(an_rva)
    oo = r2o(ao_rva)
    entries = []
    for i in range(nnames):
        nrva = struct.unpack_from("<I", d, no + i * 4)[0]
        nm = cstr(r2o(nrva))
        ordv = struct.unpack_from("<H", d, oo + i * 2)[0] + ordbase
        entries.append((ordv, nm))
    entries.sort()
    print("; auto-generated by gen_def.py from %s" % sys.argv[1])
    print("EXPORTS")
    for ordv, nm in entries:
        print("%s=%s.%s @%d" % (nm, target, nm, ordv))

if __name__ == "__main__":
    main()
